### ISSUE TITLE
udp bind "not found error"

### ISSUE THREAD

**Issue by dominictarr** [socketsupply/socket-api#20]
udp bind should return this, but it returned a weird `{err:}` object, but that error is also weird.

https://github.com/socketsupply/io/blob/master/dgram.js#L141

![image](https://user-images.githubusercontent.com/259374/183614835-442df066-c6f1-4dee-8bde-f36faf3dd688.png)

```
err: NotFoundError: Not found
column: 10
line: 56431
message: "Not found"
sourceURL: "file:///home/dominic/c/dogfood/build/linux/dogfood-dev_v0.0.1-1_amd64/opt/dogfood-dev/index.js"
stack: "rr@file:///home/dominic/c/dogfood/build/linux/dogfood-dev_v0.0.1-1_amd64/opt/dogfood-dev/index.js:56431:1…"
url: "ipc://udpBind?serverId=4305043373530229426&address=0.0.0.0&port=3456&reuseAddr=false&ipv6Only=false&index=0&seq=R16"
```

**Comment by dominictarr** [comment]
seems to come from here:

https://github.com/socketsupply/socket-sdk/blob/dev/src/linux.hh#L263-L270

**Comment by heapwolf** [comment]
turns out its a bad ipc route, I have a PR open in the socket-sdk repo that fixes this so I'll close this one.
